name: Villa Uma Buluh   - Canggu
favicon: null
layout_spectrum: 0.75632
typography_spectrum: 0.53735
author:
  name: 'roberto '
  email: roberto@isolaasia.com
  url: www.isolaasia.com
title: 'Villa Buluh  - Jalan uma buluh ,3  Canggu  Bali'
description: "\_IDR 6,100.000.000  USD  450.000"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-83295519-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: 'https://www.facebook.com/isolaasia/'
color:
  brandColors:
    - '#ffffff'
    - '#c3b296'
    - '#2b2320'
    - '#4f4a44'
    - '#826a52'
  brandStrength: 0.5
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
