name: Isolaasia
favicon: null
layout_spectrum: 0.179
typography_spectrum: 0.47353
title: 'Freehold villa for sale  - Canggu   BALI  Jalan uma buluh ,3   Canggu   Bali'
description: Roberto
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1a5488'
    - '#8f8f8f'
    - '#1f1f1f'
    - '#e4af9b'
  brandStrength: 0.25
  lightness: 0.8125
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose: []
