typography_spectrum: 0.47353
color:
  brandColors:
    - '#ffffff'
    - '#1a5488'
    - '#8f8f8f'
    - '#1f1f1f'
    - '#e4af9b'
  brandStrength: 0.625
  lightness: 0.5
  saturation: 0.625
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.66425
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: 'roberto '
  email: roberto@isolaasia.com
  url: www.isolaasia.com
name: Isolaasia
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Freehold villa for sale -Bali
description: "\_IDR 6,100.000.000"
purpose: []
