name: Canggu - Bali
favicon: null
layout_spectrum: 0.66425
typography_spectrum: 0.47353
author:
  name: 'roberto '
  email: roberto@isolaasia.com
  url: www.isolaasia.com
title: 'Freehold villa for sale -Bali   '
description: "\_IDR 6,100.000.000"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1a5488'
    - '#8f8f8f'
    - '#1f1f1f'
    - '#e4af9b'
  brandStrength: 0.625
  lightness: 0.5
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
