name: Isolaasia
favicon: null
layout_spectrum: 0.5462514467071742
typography_spectrum: 0.038483513751998544
title: Freehold villa for sale  - Canggu   BALI
description: Roberto
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5
  lightness: 0.33049255749210715
  saturation: 0.009853353258222342
  rhythmicContrast: 0.5407279678620398
purpose: []
