name: Villa Uma Buluh   - Canggu
favicon: null
layout_spectrum: 0
typography_spectrum: 0.53735
author:
  name: 'roberto '
  email: roberto@isolaasia.com
  url: www.isolaasia.com
title: "Freehold villa for sale \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ +62 (0) 81 337 873145"
description: "\_IDR 6,100.000.000  USD  450.000"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-83295519-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: 'https://www.facebook.com/isolaasia/'
color:
  brandColors:
    - '#ffffff'
    - '#1a5488'
    - '#8f8f8f'
    - '#1f1f1f'
    - '#e4af9b'
  brandStrength: 1
  lightness: 0.8125
  saturation: 0.5625
  rhythmicContrast: 0.75
purpose: []
