name: Villa Uma Buluh   - Canggu
favicon: null
layout_spectrum: 0.24368
typography_spectrum: 0.53735
author:
  name: 'roberto '
  email: roberto@isolaasia.com
  url: www.isolaasia.com
title: "Freehold villa for sale \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ \_ +62 (0) 81 337 873145"
description: "\_IDR 6,100.000.000  USD  450.000"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-83295519-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: 'https://www.facebook.com/isolaasia/'
color:
  brandColors:
    - '#fefefe'
    - '#30150c'
    - '#6c6964'
    - '#f7ae5c'
    - '#f45e64'
  brandStrength: 0.5
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
