typography_spectrum: 0.53735
color:
  brandColors:
    - '#ffffff'
    - '#c3b296'
    - '#2b2320'
    - '#4f4a44'
    - '#826a52'
  brandStrength: 0.5
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: 'https://www.facebook.com/isolaasia/'
layout_spectrum: 0.75632
analytics:
  google: UA-83295519-1
  facebook: null
  twitter: null
author:
  name: 'roberto '
  email: roberto@isolaasia.com
  url: www.isolaasia.com
name: Villa Uma Buluh   - Canggu
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: "FOR SALE \_ \_ \_ \_ \_ +62 (0) 81 337 873145"
description: "\_IDR 6,100.000.000  USD  450.000"
purpose: []
