name: Isolaasia
favicon: null
layout_spectrum: 0.5462514467071742
typography_spectrum: 0.038483513751998544
title: Freehold villa for sale  - Canggu   BALI
description: Roberto
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b6a68c'
    - '#917659'
    - '#5a3f2a'
    - '#fffbec'
    - '#251c13'
  brandStrength: 0.1875
  lightness: 1
  saturation: 0.5625
  rhythmicContrast: 0.75
purpose: []
